# dbtype - inmemory | postgres
# default - inmemory
db_type: postgres

# path to log file
# default - calendar.log in the current dir
log_file: /dev/stdout

# loglevel - none | error |  warn | info | debug
# default - info
log_level:

# ip:port for listening http
# default - localhost:8080
http_listen:

# ip:port for listening gRPC
# default - localhost:50051
grpc_listen:

# dsn for db - no default, need to set here
dsn: postgres://testuser:123456@Klim.go:5432/calendar

# rabbit connection - no default, need to set here
rabbit: amqp://testuser:123456@Klim.go:5672/

# publisher scan db timeout - default 1s
pub_timeout: 3s