version: '3'
services:

  calendar-http-server:
    build:
      context: .
      dockerfile: deployments/docker/http_server/Dockerfile
    container_name: calendar-http-alpine
    restart: always
    image: calendar-http-server
    depends_on:
      - calendar-db
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - calendar

  calendar-grpc-server:
    build:
      context: .
      dockerfile: deployments/docker/grpc_server/Dockerfile
    container_name: calendar-grpc-alpine
    restart: always
    image: calendar-grpc-server
    depends_on:
      - calendar-db
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - calendar

  calendar-alert-scheduler:
    build:
      context: .
      dockerfile: deployments/docker/alert_scheduler/Dockerfile
    container_name: calendar-alert-scheduler
    restart: always
    image: calendar-alert-scheduler
    depends_on:
      - calendar-db
      - calendar-queue
    networks:
      - calendar

  calendar-alert-sender:
    build:
      context: .
      dockerfile: deployments/docker/alert_sender/Dockerfile
    container_name: calendar-alert-sender
    restart: always
    image: calendar-alert-sender
    depends_on:
      - calendar-db
      - calendar-queue
    networks:
      - calendar

  calendar-db:
    container_name: postgres-alpine
    restart: always
    image: postgres:alpine
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: calendar
      LANG: ru_RU.utf8
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      calendar:
        aliases:
          - db

  calendar-queue:
    container_name: rabbit-alpine
    restart: always
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: calendar
      RABBITMQ_DEFAULT_PASS: 123456
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      calendar:
        aliases:
          - queue

networks:
  calendar: