version: '3'
services:
  calendar-db:
    container_name: postgres-alpine
    restart: always
    image: postgres:9.6.16-alpine
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: calendar
      LANG: ru_RU.utf8
    expose:
      - 5432
    ports:
      - 5432:5432

  calendar-queue:
    container_name: rabbit-alpine
    restart: always
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: calendar
      RABBITMQ_DEFAULT_PASS: 123456
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672