{
 "title": "Shop v3 k8s",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Ingress (nginx)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Rate 5xx (nginx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "RPS (nginx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Latancy by endpoint (nginx) - 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, path) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latancy by endpoint (nginx) - 0.95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latancy by endpoint (nginx) - 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, path) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Error Rate (pods)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (increase(chi_requests_total{code=\"Internal Server Error\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "RPS (pods)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(chi_requests_total[1m]))",
     "legendFormat": "RPS {{path}}"
    }
   ]
  },
  {
   "title": "Latancy by endpoint (pods) - 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, path) (rate(chi_request_duration_milliseconds_bucket[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latancy by endpoint (pods) - 0.95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(chi_request_duration_milliseconds_bucket[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latancy by endpoint (pods) - 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, path) (rate(chi_request_duration_milliseconds_bucket[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}