stages:
  - linters_and_tests
  - build
  - deploy

golangci-lint:
  stage: linters_and_tests
  image: golangci/golangci-lint
  script:
    - chmod +x ./build/ci/run_linters.sh
    - ./build/ci/run_linters.sh

unit-test:
  stage: linters_and_tests
  image: golang:1.13
  script:
    - go test -v -cover ./... -race
    - go get -u github.com/jstemmer/go-junit-report
    - go test -v -cover ./... 2>&1 | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

#integration-test:
#  stage: linters_and_tests
#  services: (1:04:30)
#    - ...
#    - ...
#  script:
#    - make up/test

buildapp:
  stage: build
  image: golang:1.13
  script:
    - go build -o image-previewer .
  artifacts:
    paths:
      - image-previewer

deploy:
  stage: deploy
  script:
    - echo "I'm deploy"
  when: manual
  only:
    - master

