image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - linters_and_tests
  - build
  - deploy

golangci-lint:
  stage: linters_and_tests
  image: golangci/golangci-lint
  script:
    - chmod +x ./build/ci/run_linters.sh
    - ./build/ci/run_linters.sh

unit-test:
  stage: linters_and_tests
  image: golang:1.13
  script:
    - go test -v -race `go list ./... | grep -v integration_tests`
    - ./go_test_coverage.sh
    - go get -u github.com/jstemmer/go-junit-report
    - go test -v `go list ./... | grep -v integration_tests` 2>&1 | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

integration-test:
  stage: linters_and_tests
  script:
    - make test

buildapp:
  stage: build
  image: golang:1.13
  script:
    - make build
  artifacts:
    paths:
      - ./app/image-previewer
      - ./app/image-previewer-cli
      - ./app/load-test-client

deploy:
  stage: deploy
  script:
    - echo "I'm deploy"
  when: manual
  only:
    - master

