# logger - logstd | logrus
# default - logstd
logger: logrus

# path to and name for log file
# default - previewer.log in the current dir
log_file: /dev/stderr

# loglevel - none | error |  warn | info | debug
# default - info
log_level: debug

# ip:port for listening http
# default - :8080
http_listen:

# ip:port for listening prometheus recorder
# default - :9180
prometheus_listen:

# previewer algorithm - xdraw | nfnt_crop
# default - xdraw
previewer: nfnt_crop

# interpolation for resizing
# 0 - NearestNeighbor
# 1 - Bilinear
# 2 - Bicubic, 3 - MitchellNetravali, 4 - Lanczos2, 5 - Lanczos3 (all is for nfnt_crop only)
# 6 - ApproxBiLinear (xdraw only)
# 7 - CatmullRom     (xdraw only)
# default - 0
interpolation: 1

# skip proxy below headers (every header on new line with starting -, any case)
# default - no skip any
no_proxy_headers:
  - user-agent

# image url encoder algorithm - md5 | sha1 | sha256
# default - md5
img_url_encoder:

# cache algorithm - lru | nolimit (w/o deleting old items)
# default - lru
cache: #nolimit

# max cache items
# default - 128
max_cache_items: 4

# storage system - disk | inmemory
# default - disk
storage: #inmemory

# path to storage for disk system
# default - 'cache' dir in the current path - will be created if not exists
storage_path:
