version: '3'
services:

  image-previewer-http-server:
    build:
      context: .
      dockerfile: build/package/docker/image_previewer/Dockerfile
    container_name: image-previewer-http-server
    restart: always
    command: make run
    image: image-previewer-http-server
    expose:
      - 8080
      - 9180
    ports:
      - 8080:8080
      - 9180:9180
    networks:
      image-previewer:
        aliases:
          - http-server

  image-previewer-prometheus:
    container_name: image-previewer-prometheus
    image: prom/prometheus
    volumes:
      - ./build/package/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - image-previewer-http-server
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - image-previewer

networks:
  image-previewer: