apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-shop-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: hello-shop-app
    template:
       metadata:
          labels:
             app: hello-shop-app
       spec:
          containers:
          - name: hello-shop
            image: evaklim/shop:0.1
            ports:
              - name: web
                containerPort: 8000